### ISSUE TITLE
Image data model schema

### ISSUE THREAD

**Issue by isaacncz** [yenyee912/metadata-api#1]
at the moment only few parameters are as listed: #1 
-contractAddress
-description
-fileName
-filePath
-createdAt

**Comment by yenyee912** [comment]
change description into metadata/ attributes[], and add in several objects like:
- type (land/ house/ decorations etc)
- coordinates,
- other NFT features: 
1. houseType: [bungalow, house, apartment, cottage] 
2. color/ designStyle/ theme

Reference: samurai](https://metadata-api.samuraidoge.net/5562)
{"animation_url":"https://ipfs.io/ipfs/QmTKS9rth16CsLewkVMsgokYfyKMfNtnnEzWUaTAAfJcEU",
"attributes":[
{"trait_type":"Background","value":"fuji"},
{"trait_type":"Season","value":"autumn"},
{"trait_type":"Character","value":"female"},
{"trait_type":"Character Color","value":"black"},
{"trait_type":"Expression","value":"smile"},
{"trait_type":"Armor Male","value":"0"},
{"trait_type":"Armor Female","value":"design 03"},
{"trait_type":"Armor Color","value":"sapphire"},
{"trait_type":"Sashimono","value":"floral 4"},
{"trait_type":"Sashimono Color","value":"amethyst"},
{"trait_type":"Food","value":"0"}],
"image":"https://ipfs.io/ipfs/QmWeF7sTnpDZ8dwPcKkFsnUtvyj2amam7rAWABordVFuwX",
"imageHash":"a7af49ccdd9a84cb87fcf6762712a2c2103db9909414918d5f85b9808d8c45f6",
"name":"",
"tokenId":5562}

**Comment by yenyee912** [comment]
The attributes completely rely on TomYam house/ land design, I think still waiting this from them...

**Comment by isaacncz** [comment]
sample output json as follows:
```
{
    "msg": "Successfully upload image.",
    "data": {
        "contractAddress": 12344,
        "metadata": [
            {
                "trait_type": "head",
                "value": "blue",
                "_id": ""
            },
            {
                "trait_type": "nose",
                "value": "green",
                "_id": ""
            }
        ],
        "createdAt": "2022-03-22T04:17:14.056Z",
        "_id": "",
        "filePath": "/images/12344.gif",
        "fileName": "12344.gif",
        "__v": 0
    }
}
```

**Comment by isaacncz** [comment]
sample input json as follow
![image](https://user-images.githubusercontent.com/49158607/159407478-0627d84e-da76-4d3a-8178-ebfa11e057ad.png)

**Comment by isaacncz** [comment]
sample model schema
```
const metadataSchema = new Schema({
    trait_type: {
        type: String,
        required: true
    },
    value: {
        type: String,
        required: true
    }
})

const ImageSchema = new Schema({
    contractAddress: {
        required: true,
        type: Number,
    },
    metadata: [metadataSchema],
    // for multiple uploads
    fileName: {
        required: true,
        type: String,
    },
    filePath: {
        required: true,
        type: String,
    },
    createdAt: {
        default: Date.now(),
        type: Date,
    },
});
```

**Comment by yenyee912** [comment]
all good! Thanks, can add in IPFS link after this
