### ISSUE TITLE
To upload json and tmx file

### ISSUE THREAD

**Issue by isaacncz** [yenyee912/metadata-api#3]
- to generate for the particular file when saving to the database

- to overwrite or delete old entry and replace with new entry

**Comment by isaacncz** [comment]
-to upload 2 files along with metadata
-file naming scheme as follows:
eg:
<Date.now()>-<token_id>.<extension>
- "1648799267853-123.json",
-  "1648799267853-123.tmx"

-token_id is being used to check whether entry exist and update existing entry

sample output json 
`{
    "msg": "Successfully upload files.",
    "data": {
        "file_name": [
            "1648799611337-12345.tmx",
            "1648799611337-12345.json"
        ],
        "file_path": [
            "/maps/1648799611337-12345.tmx",
            "/maps/1648799611337-12345.json"
        ],
        "created_at": "2022-04-01T07:53:03.000Z",
        "_id": "",
        "contract_address": "0x12345",
        "metadata": [
            {
                "_id": "",
                "trait_type": "head",
                "value": "blue676"
            },
            {
                "_id": "",
                "trait_type": "nose",
                "value": "green"
            }
        ],
        "token_id": "12345",
        "ipfs_url": "ipfs://asdasd.asdasdasd.asdasd",
        "property_privacy": "657567",
        "__v": 0
    }
}`

**Comment by yenyee912** [comment]
**metadata.json** no problem, can proceed with the GET function with
1. contract address
2. token id

Then do the upload POST and PUT calls with
1. must validate if 2 different extensions of files are attached

**Comment by isaacncz** [comment]
checking for file format .json and .tmx is done, meanwhile ensuring user uploading corresponding files can be performed in frontend as well
